Put vim on a diet, remove tmuxinator.

diff --git a/bin/cask-upgrade b/bin/cask-upgrade
--- a/bin/cask-upgrade
+++ b/bin/cask-upgrade
@@ -1,26 +1,30 @@
 #!/usr/bin/env bash
 
-(set -x; brew update;)
+echo >&2 "Do NOT use this, as it can screw up Anaconda and delete your shit!"
+echo >&2 "Also, may also screw with Calibre."
+exit -1
 
-(set -x; brew cleanup;)
-(set -x; brew cask cleanup;)
+# (set -x; brew update;)
 
-red=`tput setaf 1`
-green=`tput setaf 2`
-reset=`tput sgr0`
+# (set -x; brew cleanup;)
+# (set -x; brew cask cleanup;)
 
-casks=( $(brew cask list) )
+# red=`tput setaf 1`
+# green=`tput setaf 2`
+# reset=`tput sgr0`
 
-for cask in ${casks[@]}
-do
-    version=$(brew cask info $cask | sed -n "s/$cask:\ \(.*\)/\1/p")
-    installed=$(find "/usr/local/Caskroom/$cask" -type d -maxdepth 1 -maxdepth 1 -name "$version")
+# casks=( $(brew cask list) )
 
-    if [[ -z $installed ]]; then
-        echo "${red}${cask}${reset} requires ${red}update${reset}."
-        (set -x; brew cask uninstall $cask --force;)
-        (set -x; brew cask install $cask --force;)
-    else
-        echo "${red}${cask}${reset} is ${green}up-to-date${reset}."
-    fi
-done
+# for cask in ${casks[@]}
+# do
+    # version=$(brew cask info $cask | sed -n "s/$cask:\ \(.*\)/\1/p")
+    # installed=$(find "/usr/local/Caskroom/$cask" -type d -maxdepth 1 -maxdepth 1 -name "$version")
+
+    # if [[ -z $installed ]]; then
+        # echo "${red}${cask}${reset} requires ${red}update${reset}."
+        # (set -x; brew cask uninstall $cask --force;)
+        # (set -x; brew cask install $cask --force;)
+    # else
+        # echo "${red}${cask}${reset} is ${green}up-to-date${reset}."
+    # fi
+# done
